"""Validate catalog.json and render the catalog's generated Markdown (Python standard library only).

    python3 generate.py --write    # regenerate source.md, variants.md, README.md, RIGHTS.md, ../README.md
    python3 generate.py --check    # verify generated files, folders, digests, licensed copies, and ignores
"""

import argparse
import hashlib
import json
import os
import re
import subprocess
import sys
from collections import Counter
from pathlib import Path
from urllib.parse import urlparse

import digest_check

ROOT = Path(__file__).resolve().parent
REPO = ROOT.parent
REPOSITORY = "IraLeeBell/models"
SUPPORTED = "https://docs.github.com/en/copilot/reference/ai-models/supported-models"
COMPARISON = "https://docs.github.com/en/copilot/reference/ai-models/model-comparison"
RETIRED = "https://docs.github.com/en/copilot/reference/ai-models/supported-models#model-retirement-history"
GENERATED = "<!-- Generated by models/generate.py from models/catalog.json. Edit the catalog, then run `python3 generate.py --write`. -->"

# Owner hosts (and required path prefixes) from which each publisher's documents may be fetched.
PUBLISHER_HOSTS = {
    "OpenAI": {"deploymentsafety.openai.com": "/", "cdn.openai.com": "/"},
    "Anthropic": {"www.anthropic.com": "/", "www-cdn.anthropic.com": "/", "assets.anthropic.com": "/"},
    "Google DeepMind": {"storage.googleapis.com": "/deepmind-media/"},
    "Microsoft": {"microsoft.ai": "/pdf/"},
    "Moonshot AI": {"raw.githubusercontent.com": "/MoonshotAI/", "huggingface.co": "/moonshotai/"},
    "xAI": {"media.x.ai": "/"},
}
PROVIDER_PUBLISHER = {
    "OpenAI": "OpenAI", "Anthropic": "Anthropic", "Google": "Google DeepMind",
    "Microsoft": "Microsoft", "Moonshot AI": "Moonshot AI", "xAI": "xAI",
}
# Publisher terms reviewed for documents without an explicit redistribution license.
TERMS = {
    "OpenAI": (
        "OpenAI Terms of Use", "https://openai.com/policies/terms-of-use/",
        "The terms govern use of OpenAI's services and reserve OpenAI's rights. Neither they, the "
        "Deployment Safety Hub, nor the PDFs grant a license to republish a system card.",
    ),
    "Anthropic": (
        "Anthropic Consumer Terms of Service", "https://www.anthropic.com/legal/consumer-terms",
        "The terms govern use of Anthropic's services. Neither they, Anthropic's system-card pages, "
        "nor the PDFs grant a license to republish a system card.",
    ),
    "Google DeepMind": (
        "Google Terms of Service", "https://policies.google.com/terms",
        "The terms reserve Google's intellectual-property rights. No redistribution grant was found "
        "for Gemini model-card PDFs.",
    ),
    "Microsoft": (
        "Microsoft Terms of Use", "https://www.microsoft.com/en-us/legal/terms-of-use",
        "The Documents clause restricts copying or posting documents from Microsoft sites on another "
        "network. The License field inside each MAI card concerns the model, not the PDF.",
    ),
    "xAI": (
        "xAI Terms of Service", "https://x.ai/legal/terms-of-service",
        "The terms govern use of xAI's services. Neither they nor the PDFs grant a license to "
        "republish a Grok model card.",
    ),
}
LIFECYCLE = {
    "current": "Current",
    "limited": "Limited (annual Pro/Pro+ only)",
    "utility": "Utility only (not selectable)",
    "retired": "Retired",
}
CLI = {True: "Yes", False: "No", "auto-only": "Auto selection only"}
SLUG = re.compile(r"[a-z0-9]+(?:[.-][a-z0-9]+)*")
SHA = re.compile(r"[0-9a-f]{64}")
REVISION = re.compile(r"[0-9a-f]{40}")
DATE = re.compile(r"\d{4}-\d{2}-\d{2}")
PUBLISHED = re.compile(r"\d{4}-\d{2}(?:-\d{2})?")
# Strings that must never appear in authored or generated public files.
BANNED = re.compile(r"internal[- ]only|-internal\b|\bFinOps\b|premium request", re.IGNORECASE)


class CatalogError(ValueError):
    """catalog.json is inconsistent."""


def owner_url(url, publisher):
    parsed = urlparse(url)
    prefix = PUBLISHER_HOSTS[publisher].get(parsed.hostname or "")
    return parsed.scheme == "https" and prefix is not None and parsed.path.startswith(prefix)


def load_catalog(path=ROOT / "catalog.json"):
    catalog = json.loads(Path(path).read_text(encoding="utf-8"))

    def need(condition, message):
        if not condition:
            raise CatalogError(message)

    need(catalog.get("schema_version") == 2, "schema_version must be 2")
    for key in ("checked_at", "app_picker_checked_at"):
        need(DATE.fullmatch(str(catalog.get(key, ""))), f"{key} must be YYYY-MM-DD")
    for key in ("docs_revision", "docs_tables_commit"):
        need(REVISION.fullmatch(str(catalog.get(key, ""))), f"{key} must be a full commit SHA")
    documents, models = catalog["documents"], catalog["models"]
    for doc_id, doc in documents.items():
        need(SLUG.fullmatch(doc_id), f"unsafe document id {doc_id}")
        need(doc.get("publisher") in PUBLISHER_HOSTS, f"{doc_id}: unknown publisher")
        need(doc.get("format") in ("pdf", "markdown"), f"{doc_id}: format must be pdf or markdown")
        for key in ("title", "title_check", "url", "retrieved"):
            need(isinstance(doc.get(key), str) and doc[key].strip(), f"{doc_id}: {key} is required")
        need(DATE.fullmatch(doc["retrieved"]), f"{doc_id}: retrieved must be YYYY-MM-DD")
        need(PUBLISHED.fullmatch(doc.get("date") or "") or (doc.get("date") is None and doc.get("date_note")),
             f"{doc_id}: date must be YYYY-MM[-DD], or null with a date_note")
        need(SHA.fullmatch(doc.get("sha256", "")), f"{doc_id}: sha256 must be 64 hex digits")
        need(isinstance(doc.get("bytes"), int) and doc["bytes"] > 0, f"{doc_id}: bytes is required")
        if doc["format"] == "pdf":
            need(isinstance(doc.get("pages"), int) and doc["pages"] > 0, f"{doc_id}: pages is required")
        else:
            need(doc.get("pages") is None, f"{doc_id}: a non-PDF document has no page count")
        for url in [doc["url"], doc.get("resolved_url")] + [r["url"] for r in doc.get("other_revisions", [])]:
            if url:
                need(owner_url(url, doc["publisher"]), f"{doc_id}: {url} is not an owner URL")
        if doc.get("landing_url"):
            need(urlparse(doc["landing_url"]).scheme == "https", f"{doc_id}: landing_url must be https")
        for revision in doc.get("other_revisions", []):
            need(SHA.fullmatch(revision.get("sha256", "")) and revision.get("note"),
                 f"{doc_id}: other_revisions need sha256 and note")
        need(doc.get("rights") in ("granted", "not-granted"), f"{doc_id}: rights must be granted or not-granted")
        if doc["rights"] == "granted":
            for key in ("rights_basis", "license_file", "license_name", "license_url", "license_sha256", "copyright"):
                need(doc.get(key), f"{doc_id}: granted rights need {key}")
        else:
            need(doc["publisher"] in TERMS, f"{doc_id}: no terms recorded for {doc['publisher']}")

    slugs, names = Counter(m["slug"] for m in models), Counter(m["name"] for m in models)
    need(max(slugs.values()) == 1 and max(names.values()) == 1, "duplicate model slug or name")
    used = set()
    for model in models:
        slug = model["slug"]
        need(SLUG.fullmatch(slug), f"unsafe slug {slug}")
        need(model.get("provider") in PROVIDER_PUBLISHER, f"{slug}: unknown provider")
        need(model.get("lifecycle") in LIFECYCLE, f"{slug}: unknown lifecycle")
        need(model.get("cli") in CLI, f"{slug}: cli must be true, false, or auto-only")
        need(isinstance(model.get("summary"), str) and model["summary"], f"{slug}: summary is required")
        need(isinstance(model.get("scope"), str) and model["scope"], f"{slug}: scope is required")
        if model["lifecycle"] in ("current", "limited"):
            need(isinstance(model.get("app_picker_observed"), bool) and isinstance(model.get("app_auto"), bool),
                 f"{slug}: current models need app_picker_observed and app_auto")
            need(bool(model.get("copilot_id")) == model["app_picker_observed"],
                 f"{slug}: copilot_id is recorded only for models observed in the app picker")
        if model["lifecycle"] in ("retired", "limited"):
            need(DATE.fullmatch(model.get("retired_on", "")), f"{slug}: retired_on is required")
        if model["lifecycle"] == "retired":
            need(REVISION.fullmatch(model.get("last_listed_revision", "")), f"{slug}: last_listed_revision is required")
        doc_id = model.get("document")
        if doc_id is None:
            need(model.get("card_note"), f"{slug}: explain the missing publisher document in card_note")
        else:
            need(doc_id in documents, f"{slug}: unknown document {doc_id}")
            need(documents[doc_id]["publisher"] == PROVIDER_PUBLISHER[model["provider"]],
                 f"{slug}: document publisher does not match provider")
            need(model.get("scope_terms"), f"{slug}: scope_terms are required with a document")
            used.add(doc_id)
        for supplement in model.get("supplements", []):
            need(supplement in documents and supplement != doc_id, f"{slug}: bad supplement {supplement}")
            used.add(supplement)
        for related in model.get("related", []):
            need(related["slug"] in slugs, f"{slug}: related slug {related['slug']} is not in the catalog")
    need(used == set(documents), f"unused documents: {sorted(set(documents) - used)}")
    return catalog


def users(catalog):
    found = {doc_id: [] for doc_id in catalog["documents"]}
    for model in catalog["models"]:
        if model.get("document"):
            found[model["document"]].append((model, "primary"))
        for supplement in model.get("supplements", []):
            found[supplement].append((model, "supplement"))
    return found


def tables_url(revision, table="model-supported-clients.yml"):
    return f"https://github.com/github/docs/blob/{revision}/data/tables/copilot/{table}"


def commit_url(revision):
    return f"https://github.com/github/docs/commit/{revision}"


def size(value):
    return f"{value:,} bytes ({value / 1_048_576:.1f} MiB)" if value >= 1_048_576 else f"{value:,} bytes"


def dated(doc):
    return doc["date"] or "undated"


def doc_label(doc):
    if doc["format"] == "pdf":
        return f"PDF, {doc['pages']} pages"
    return "Markdown model card (owner's Hugging Face README; not a PDF)"


def files_for(model, catalog):
    """Return (committed, local_only) file descriptions for a model folder."""
    committed = [("digest.md", "original digest (this repository's MIT license)"),
                 ("digest.json", "structured version of the digest"),
                 ("source.md", "this provenance record (generated)"),
                 ("variants.md", "Copilot identifiers and related entries (generated)")]
    local = []
    doc = catalog["documents"].get(model.get("document"))
    if doc and doc["format"] == "pdf":
        pair = [("system-card.pdf", "the publisher's unmodified PDF"),
                ("system-card.md", "complete page-marked Markdown extraction of that PDF")]
        (committed if doc["rights"] == "granted" else local).extend(pair)
    elif doc:
        committed.append(("model-card.md", "the owner's Markdown model card, byte-for-byte"))
    if doc and doc["rights"] == "granted":
        committed.append((doc["license_file"], f"the publisher's {doc['license_name']}, which must accompany the copy"))
    for supplement in model.get("supplements", []):
        local.append((f"supplements/{supplement}.pdf", f"supplement PDF ({catalog['documents'][supplement]['title']})"))
        local.append((f"supplements/{supplement}.md", "page-marked extraction of the supplement"))
    return committed, local


def approval(doc):
    return (f"Written permission from {doc['publisher']} (the copyright holder) to publish, in the public "
            f"repository `{REPOSITORY}`, (1) an unmodified copy of the PDF \"{doc['title']}\" "
            f"(SHA-256 `{doc['sha256']}`) and (2) a complete verbatim Markdown extraction of it, with "
            "attribution. The grant should name the document or cover all of the publisher's system or "
            "model cards, and state any notice that must accompany the copy.")


def document_section(doc_id, doc, heading):
    lines = [heading, "", "| Field | Value |", "| --- | --- |",
             f"| Publisher | {doc['publisher']} |",
             f"| Title | {doc['title']} |",
             f"| Document date | {dated(doc)}{' (' + doc['date_note'] + ')' if doc.get('date_note') else ''} |",
             f"| Format | {doc_label(doc)} |",
             f"| Owner URL | <{doc['url']}> |"]
    if doc.get("resolved_url"):
        lines.append(f"| Redirects to | <{doc['resolved_url']}> |")
    if doc.get("landing_url"):
        lines.append(f"| Publisher landing page | <{doc['landing_url']}> |")
    lines += [f"| Retrieved | {doc['retrieved']} |",
              f"| Size | {size(doc['bytes'])} |",
              f"| SHA-256 | `{doc['sha256']}` |",
              f"| Catalog document ID | `{doc_id}` |", ""]
    if doc.get("other_revisions"):
        lines += ["Other revisions observed at owner URLs on the retrieval date (not used):", "",
                  "| URL | Size | Pages | SHA-256 | Note |", "| --- | --- | --- | --- | --- |"]
        for revision in doc["other_revisions"]:
            lines.append(f"| <{revision['url']}> | {revision['bytes']:,} bytes | {revision.get('pages') or ''} | "
                         f"`{revision['sha256']}` | {revision['note']} |")
        lines.append("")
    return lines


def rights_section(doc):
    if doc["rights"] == "granted":
        return [f"- **Decision: granted.** The complete document is committed with its license notice.",
                f"- **Basis:** {doc['rights_basis']}",
                f"- **License:** [{doc['license_name']}]({doc['license_url']}); copy in "
                f"[`{doc['license_file']}`]({doc['license_file']}) (SHA-256 `{doc['license_sha256']}`).",
                f"- **Attribution:** \"{doc['title']}\" by {doc['publisher']}, {dated(doc)}, <{doc['url']}>. "
                f"{doc['copyright']}; redistributed unmodified under the {doc['license_name']}.",
                "- **Optional confirmation:** the license names `license@moonshot.ai` for questions.", ""]
    name, url, finding = TERMS[doc["publisher"]]
    return ["- **Decision: not granted.** The PDF and its full text are linked and reproducible locally, "
            "not committed.",
            f"- **Basis:** No redistribution license appears in the document's text, links, or metadata. "
            f"[{name}]({url}): {finding} Public availability is not permission to republish.",
            f"- **Attribution for links and digest:** \"{doc['title']}\" by {doc['publisher']}, {dated(doc)}, "
            f"<{doc['url']}>. All rights in the document belong to {doc['publisher']}.",
            f"- **Approval needed to commit it:** {approval(doc)}", ""]


def render_source(model, catalog):
    documents = catalog["documents"]
    doc_id = model.get("document")
    doc = documents.get(doc_id)
    lines = [f"# Source provenance: {model['name']}", "", GENERATED, "",
             "## Copilot availability", "", "| Field | Value |", "| --- | --- |",
             f"| Lifecycle | {LIFECYCLE[model['lifecycle']]} |",
             f"| GitHub release status | {model['release_status']} |"]
    revision = model.get("last_listed_revision", catalog["docs_revision"])
    if model["cli"] == "auto-only":
        lines.append(f"| Copilot CLI | Auto selection only: in GitHub's [Auto model selection table]"
                     f"({tables_url(revision, 'auto-model-selection.yml')}), not yet a row in the per-client table |")
    else:
        lines.append(f"| Copilot CLI | {CLI[model['cli']]} ([per-client table]({tables_url(revision)})) |")
    if model["lifecycle"] in ("current", "limited"):
        picker = (f"Listed as `{model['copilot_id']}`" if model["app_picker_observed"] else "Not listed")
        lines += [f"| Copilot app model picker | {picker} (observed {catalog['app_picker_checked_at']}) |",
                  f"| Copilot app Auto selection | {'Eligible' if model['app_auto'] else 'Not listed'} "
                  f"([Auto table]({tables_url(revision, 'auto-model-selection.yml')})) |"]
    if model.get("retired_on"):
        lines.append(f"| GitHub retirement date | {model['retired_on']} ([retirement history]({RETIRED})) |")
    if model["lifecycle"] == "retired":
        lines.append(f"| Last listed in GitHub docs | [`{revision[:7]}`]({commit_url(revision)}) "
                     f"([frozen per-client table]({tables_url(revision)})) |")
    lines += [f"| Roster checked | {catalog['checked_at']} at github/docs [`{catalog['docs_revision'][:7]}`]"
              f"({commit_url(catalog['docs_revision'])}) ([supported models]({SUPPORTED})) |", ""]
    if model.get("note"):
        lines += [model["note"], ""]

    if doc:
        lines += document_section(doc_id, doc, "## Publisher document")
        lines += [f"**Scope for this model:** {model['scope']}", ""]
        lines += [f"**Scope check:** the downloaded document's first pages contain \"{doc['title_check']}\" and "
                  f"its text contains {', '.join(repr(t) for t in model['scope_terms'])}.", ""]
        if model.get("card_note"):
            lines += [model["card_note"], ""]
        for supplement in model.get("supplements", []):
            lines += document_section(supplement, documents[supplement], f"### Supplement: {documents[supplement]['title']}")
            lines += rights_section(documents[supplement])
        lines += ["## Redistribution permission", ""] + rights_section(doc)
    else:
        lines += ["## Publisher document", "",
                  "**None.** No publisher system card or model card exists for this model.", "",
                  f"**Scope:** {model['scope']}", "", model["card_note"], ""]

    committed, local = files_for(model, catalog)
    lines += ["## Files", "", "Committed in this folder:", ""]
    lines += [f"- [`{name}`]({name}): {text}" for name, text in committed]
    if local:
        lines += ["", "Local only (Git-ignored; create them with the workflow below):", ""]
        lines += [f"- `{name}`: {text}" for name, text in local]
    lines.append("")
    if doc:
        lines += ["## Reproduce or refresh locally", "", "```sh", "cd models",
                  "python3 -m pip install -r requirements-local.txt",
                  f"python3 local_cards.py --model {model['slug']}", "```", "",
                  "The script downloads from the owner URL, accepts only the publisher's hosts, checks the "
                  "content type, file signature, SHA-256, title, and model scope terms, then writes the files "
                  "above. A SHA-256 mismatch means the publisher revised the document; re-verify its scope "
                  "and update the catalog before trusting the new copy.", ""]
    return "\n".join(lines).rstrip() + "\n"


def link(model, target="digest.md", prefix="../"):
    return f"[{model['name']}]({prefix}{model['slug']}/{target})"


def status(model):
    label = LIFECYCLE[model["lifecycle"]]
    return f"{label} {model['retired_on']}" if model["lifecycle"] == "retired" else label


def render_variants(model, catalog):
    documents, by_slug = catalog["documents"], {m["slug"]: m for m in catalog["models"]}
    lines = [f"# Variants and related entries: {model['name']}", "", GENERATED, "",
             "## Copilot identifiers and settings", "", "| Surface | Identifier or setting | Evidence |",
             "| --- | --- | --- |",
             f"| GitHub supported-models tables | \"{model['name']}\" | [supported models]({SUPPORTED}) |"]
    if model.get("copilot_id"):
        efforts = model.get("app_reasoning_efforts") or []
        lines += [f"| Copilot app model picker | `{model['copilot_id']}` | observed {catalog['app_picker_checked_at']} |",
                  f"| App reasoning-effort options | {', '.join(efforts) if efforts else 'none offered'} | app picker |",
                  f"| App long-context option | {'offered' if model.get('app_long_context') else 'not offered'} | app picker |"]
    elif model["lifecycle"] in ("current", "limited"):
        lines.append(f"| Copilot app model picker | not listed | observed {catalog['app_picker_checked_at']} |")
    if model["lifecycle"] in ("current", "limited"):
        lines.append(f"| App Auto selection | {'eligible' if model['app_auto'] else 'not listed'} | GitHub Auto table |")
    lines.append(f"| Copilot CLI | {CLI[model['cli']].lower()} | GitHub per-client and Auto tables |")
    lines += ["", "Reasoning-effort and context options run the same model with different settings. They are "
              "not separate models and have no separate publisher cards. Picker observations reflect one "
              "account on one date; plans, policies, and rollouts change what a user sees.", ""]

    doc_id = model.get("document")
    lines += ["## Publisher document coverage", ""]
    if doc_id:
        doc = documents[doc_id]
        lines += [f"This folder uses [{doc['title']}]({doc['url']}) ({doc['publisher']}, {dated(doc)}). "
                  f"{model['scope']}", ""]
        shared = [m for m in catalog["models"] if m["slug"] != model["slug"]
                  and (m.get("document") == doc_id or doc_id in m.get("supplements", []))]
        if shared:
            lines += ["Other folders that use the same document:", ""]
            lines += [f"- {link(m, 'variants.md')} ({status(m)}): {m['scope']}" for m in shared]
            lines.append("")
        for supplement in model.get("supplements", []):
            sdoc = documents[supplement]
            lines += [f"Supplement: [{sdoc['title']}]({sdoc['url']}) ({dated(sdoc)}).", ""]
        revisions = doc.get("other_revisions", [])
        lines += [f"Document revision used: SHA-256 `{doc['sha256']}` ({doc_label(doc)})."]
        if revisions:
            lines.append(f"{len(revisions)} other revision(s) observed at owner URLs are listed in [source.md](source.md).")
        lines.append("")
    else:
        lines += ["No publisher card exists. " + model["card_note"], ""]

    series = [by_slug[s] for s in SERIES_ORDER(catalog, model)]
    if series:
        lines += [f"## {model['series']} series in this catalog", "", "| Model | Status | Publisher document |",
                  "| --- | --- | --- |"]
        for member in series:
            mdoc = documents.get(member.get("document"))
            title = f"[{mdoc['title']}]({mdoc['url']})" if mdoc else "none"
            name = f"**{member['name']}** (this folder)" if member is model else link(member, "variants.md")
            lines.append(f"| {name} | {status(member)} | {title} |")
        lines.append("")
    if model.get("related"):
        lines += ["## Related entries", ""]
        lines += [f"- {link(by_slug[r['slug']], 'variants.md')}: {r['relation']}." for r in model["related"]]
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def SERIES_ORDER(catalog, model):
    if not model.get("series"):
        return []
    return [m["slug"] for m in catalog["models"] if m.get("series") == model["series"]]


def counts(catalog):
    models, documents = catalog["models"], catalog["documents"]
    lifecycle = Counter(m["lifecycle"] for m in models)
    formats = Counter(d["format"] for d in documents.values())
    granted = [d for d in documents.values() if d["rights"] == "granted"]
    return {
        "models": len(models), "current": lifecycle["current"], "limited": lifecycle["limited"],
        "utility": lifecycle["utility"], "retired": lifecycle["retired"],
        "documents": len(documents), "pdf": formats["pdf"], "markdown": formats["markdown"],
        "granted": len(granted), "not_granted": len(documents) - len(granted),
        "pdf_pages": sum(d["pages"] or 0 for d in documents.values()),
        "with_document": sum(1 for m in models if m.get("document")),
        "without_document": sum(1 for m in models if not m.get("document")),
        "cli": sum(1 for m in models if m["lifecycle"] in ("current", "limited") and m["cli"] is True),
        "cli_auto": sum(1 for m in models if m["lifecycle"] == "current" and m["cli"] == "auto-only"),
        "picker": sum(1 for m in models if m.get("app_picker_observed")),
        "auto": sum(1 for m in models if m.get("app_auto")),
    }


def full_text(model, catalog):
    doc = catalog["documents"].get(model.get("document"))
    if not doc:
        return "none (no card)"
    if doc["rights"] == "granted":
        name = "system-card.md" if doc["format"] == "pdf" else "model-card.md"
        return f"[committed]({model['slug']}/{name})"
    return "local workflow"


def doc_cell(model, catalog):
    doc = catalog["documents"].get(model.get("document"))
    if not doc:
        return f"[none]({model['slug']}/source.md)"
    pages = f", {doc['pages']} pp." if doc["pages"] else ", Markdown"
    return f"[{doc['title']}]({model['slug']}/source.md){pages}"


def render_index(catalog):
    c = counts(catalog)
    models = catalog["models"]
    lines = ["# Model card catalog for GitHub Copilot models (unofficial)", "", GENERATED, "",
             "> [!WARNING]",
             "> **Not a GitHub product; provided as is, without warranty, at your own risk.** The models listed "
             "here do not necessarily match what GitHub Copilot serves now or later; consult GitHub's "
             f"[supported AI models reference]({SUPPORTED}) for the authoritative list. Publisher documents and "
             "their transcriptions remain the property of their respective owners. See the "
             "[repository README](../README.md) for the full disclaimer.", "",
             f"Checked **{catalog['checked_at']}**. One folder per model that the GitHub Copilot CLI or the "
             "GitHub Copilot app offers, plus a utility model and recently retired models, each mapped to the "
             "most specific system card or model card from the model's publisher.", "",
             "## Coverage", "",
             f"- **{c['models']} model folders:** {c['current']} current, {c['limited']} limited, "
             f"{c['utility']} utility-only, {c['retired']} retired.",
             f"- **{c['documents']} publisher documents:** {c['pdf']} PDFs ({c['pdf_pages']:,} pages) and "
             f"{c['markdown']} Markdown model card. {c['with_document']} folders map to a document; "
             f"{c['without_document']} have no publisher card.",
             f"- **Full text in this repository:** {c['granted']} documents whose publisher license permits "
             f"redistribution. The other {c['not_granted']} are linked with SHA-256 provenance and can be "
             "downloaded and extracted locally; see [RIGHTS.md](RIGHTS.md).",
             f"- **Digests:** every folder has an original `digest.md` and `digest.json`, citing PDF pages "
             "(section headings for the Markdown card; owner pages for folders without a card).",
             "",
             "## How the roster was established", "",
             f"- **Copilot CLI:** the `cli` column of GitHub's [per-client table]({SUPPORTED}#supported-ai-models-per-client) "
             f"({tables_url(catalog['docs_revision'])}). {c['cli']} current or limited models are rows with CLI "
             f"support; {c['cli_auto']} more (GPT-6.1 Sol) is listed only in the CLI column of the Auto model "
             "selection table.",
             f"- **Copilot app:** the per-client table has no app column, so the app's model picker was observed on "
             f"{catalog['app_picker_checked_at']}: {c['picker']} of these models were listed. GitHub's "
             f"[Auto selection table]({tables_url(catalog['docs_revision'], 'auto-model-selection.yml')}) "
             f"lists {c['auto']} as eligible for app Auto selection. Auto itself is a selector, not a model, "
             "and has no folder.",
             f"- **Release status and retirements:** GitHub's release-status table and [retirement history]({RETIRED}). "
             "Retired models link to the last github/docs revision that listed them.",
             f"- **Revision:** github/docs [`{catalog['docs_revision'][:7]}`]({commit_url(catalog['docs_revision'])}); "
             f"the model tables last changed in [`{catalog['docs_tables_commit'][:7]}`]({commit_url(catalog['docs_tables_commit'])}).",
             "- Official sources only: GitHub documentation and changelog, and each publisher's own site.", ""]

    def table(rows, columns, render):
        out = ["| " + " | ".join(columns) + " |", "|" + " --- |" * len(columns)]
        out += ["| " + " | ".join(render(m)) + " |" for m in rows]
        return out + [""]

    def scope_kind(m):
        doc = catalog["documents"].get(m.get("document") or "")
        if not doc:
            return "none"
        if doc["format"] != "pdf":
            return "markdown"
        return "dedicated" if m["name"].lower() in doc["title"].lower() else "shared"

    groups = {"none": [], "shared": [], "markdown": [], "dedicated": []}
    for m in models:
        groups[scope_kind(m)].append(m)
    lines += ["## Document scope and gaps", "",
              f"{len(groups['dedicated'])} folders map to a publisher document titled for that model. The others, "
              "and dedicated cards with a notable caveat, are listed here. Each folder's `source.md` records the "
              "pages and terms that establish scope.", ""]
    for kind, heading in (("none", "No publisher card"),
                          ("shared", "Covered by a family or shared card (title does not name the model)"),
                          ("markdown", "Owner Markdown card (no PDF published)")):
        lines += [f"**{heading}**", ""]
        for m in groups[kind]:
            detail = m.get("card_note") or m["scope"]
            if kind == "shared":
                detail = m["scope"] + (f" {m['card_note']}" if m.get("card_note") else "")
            lines.append(f"- {link(m, 'source.md', prefix='')}: {detail}")
        lines.append("")
    caveats = [m for m in groups["dedicated"] if m.get("card_note")]
    if caveats:
        lines += ["**Dedicated cards with caveats**", ""]
        lines += [f"- {link(m, 'source.md', prefix='')}: {m['card_note']}" for m in caveats]
        lines.append("")

    current = [m for m in models if m["lifecycle"] == "current"]
    lines += ["## Current models", ""]
    lines += table(current, ["Model", "Provider", "Status", "CLI", "App picker", "App Auto", "Publisher document", "Full text"],
                   lambda m: [link(m, prefix=""), m["provider"], m["release_status"], CLI[m["cli"]],
                              f"`{m['copilot_id']}`" if m.get("copilot_id") else "not listed",
                              "yes" if m["app_auto"] else "no", doc_cell(m, catalog), full_text(m, catalog)])
    other = [m for m in models if m["lifecycle"] in ("limited", "utility")]
    lines += ["## Limited and utility entries", ""]
    lines += table(other, ["Model", "Provider", "Lifecycle", "CLI", "Publisher document", "Note"],
                   lambda m: [link(m, prefix=""), m["provider"], LIFECYCLE[m["lifecycle"]], CLI[m["cli"]],
                              doc_cell(m, catalog), m.get("note", "").split(". ")[0].rstrip(".") + "."])
    lines += ["GitHub's [utility models](https://docs.github.com/en/copilot/reference/ai-models/supported-models#utility-models) "
              "power background features and cannot be selected in a model picker. Besides GPT-5.4 nano, GitHub names "
              "GPT-4o mini, GPT-4o, and GPT-4.1 as utility models; they are not rows in the per-client or "
              "release-status tables (GPT-4.1 appears in the retirement history as a selectable model), so they "
              "have no folders here.", ""]
    retired = [m for m in models if m["lifecycle"] == "retired"]
    lines += ["## Retired models (historical)", "",
              "Kept for comparison and lineage. They are no longer offered in Copilot.", ""]
    lines += table(retired, ["Model", "Provider", "Retired", "Last listed", "Publisher document", "Full text"],
                   lambda m: [link(m, prefix=""), m["provider"], m["retired_on"],
                              f"[`{m['last_listed_revision'][:7]}`]({tables_url(m['last_listed_revision'])})",
                              doc_cell(m, catalog), full_text(m, catalog)])

    lines += ["## Publisher documents", "",
              "| Document | Publisher | Date | Format | SHA-256 (prefix) | Rights | Folders |",
              "| --- | --- | --- | --- | --- | --- | --- |"]
    for doc_id, doc in catalog["documents"].items():
        folders = ", ".join(f"[`{m['slug']}`]({m['slug']}/source.md)" + (" (supplement)" if role == "supplement" else "")
                            for m, role in users(catalog)[doc_id])
        lines.append(f"| [{doc['title']}]({doc['url']}) | {doc['publisher']} | {dated(doc)} | {doc_label(doc).split(' (')[0]} | "
                     f"`{doc['sha256'][:12]}` | {'granted' if doc['rights'] == 'granted' else 'link only'} | {folders} |")
    lines.append("")

    lines += ["## Folder layout", "", "```text", "<model>/",
              "  digest.md        original digest with page (or section) citations",
              "  digest.json      the same digest as structured data (schema_version 1; see DIGESTS.md)",
              "  source.md        roster evidence, document provenance, SHA-256, rights decision (generated)",
              "  variants.md      Copilot identifiers, app settings, shared documents, series (generated)",
              "  system-card.pdf  publisher PDF          (committed only when licensed; otherwise local)",
              "  system-card.md   page-marked extraction (committed only when licensed; otherwise local)",
              "  model-card.md    owner Markdown card, when the owner publishes no PDF",
              "  LICENSE-*.txt    publisher license text, beside licensed copies",
              "  supplements/     local-only supplement PDFs and extractions", "```", "",
              "Each `system-card.md` starts with a provenance header and has one `<!-- page N of M -->` marker per "
              "PDF page. Pages where layout conversion missed text also carry the page's complete selectable text, "
              "so no selectable text is dropped. Large TeX delimiters that have no Unicode mapping in the PDF are "
              "written as the bracket or brace they draw, and the header counts them and any unmappable glyphs. "
              "Figures and text inside images are not reproduced.", "",
              "## Local download and extraction", "", "```sh", "cd models",
              "python3 -m venv .venv && . .venv/bin/activate",
              "python3 -m pip install -r requirements-local.txt",
              "python3 local_cards.py --all                    # every PDF, primary and supplements",
              "python3 local_cards.py --model grok-4.7         # one folder",
              "python3 local_cards.py --check-urls             # owner URLs still serve the cataloged files' type",
              "```", "",
              "Outputs go into each model folder and are Git-ignored unless the document's rights are `granted`. "
              "Add `--ocr` (requires Tesseract) to OCR pages without selectable text; none of the current PDFs need it. "
              "`--report report.json` records per-page conversion coverage. `--refresh` re-downloads even when a "
              "verified copy exists, and `--pdf-cache DIR` reuses previously downloaded `<sha256>.pdf` files. A "
              "SHA-256 mismatch stops the run without replacing existing files: the publisher has changed the "
              "document, so re-verify its scope and update `catalog.json` before using the new copy.", "",
              "## Maintenance", "",
              "1. **Roster.** Run `python3 roster_check.py` to compare the catalog with GitHub's current tables. "
              "Re-check the app model picker. Update `catalog.json`: add models, change `lifecycle`, and for "
              "retirements set `retired_on` and `last_listed_revision`. Bump `checked_at`, `docs_revision`, and "
              "`docs_tables_commit`.",
              "2. **Documents.** Find the publisher's most specific card for each new model and verify that it names the "
              "model. Add a `documents` entry with the owner URL, title, date, bytes, pages, SHA-256, and retrieval date. "
              "`python3 local_cards.py --model <slug>` verifies all of these. Record superseded files under `other_revisions`.",
              "3. **Rights.** Keep `rights: not-granted` unless the publisher grants redistribution in writing or by "
              "license. A granted document needs `rights_basis` and license fields, `.gitignore` negations, and the "
              "license file committed beside it.",
              "4. **Digests.** Write `digest.md` and `digest.json` following [DIGESTS.md](DIGESTS.md), then run "
              "`python3 digest_check.py <slug>` with the local extraction present.",
              "5. **Generate and verify.** `python3 generate.py --write`, then `python3 generate.py --check` and "
              "`python3 -m unittest discover -s . -p 'test_*.py'`.", ""]
    return "\n".join(lines).rstrip() + "\n"


def render_rights(catalog):
    c = counts(catalog)
    lines = ["# Publisher document rights review", "", GENERATED, "",
             f"Checked {catalog['checked_at']}. The repository's MIT license covers only its original work: "
             "digests, generated Markdown, and scripts. Publisher documents keep their own terms. A public URL is "
             "not permission to republish, and a model-weights license is not automatically a documentation "
             "license. This review is not legal advice.", "",
             f"Each of the {c['pdf']} PDFs was searched on every page, and in its links and metadata, for a "
             "redistribution notice. None contains one. The decision therefore rests on the publisher's terms or "
             "on a license published with the document.", "",
             "## By publisher", "",
             "| Publisher | Source reviewed | Decision | Documents |", "| --- | --- | --- | --- |"]
    by_publisher = {}
    for doc in catalog["documents"].values():
        by_publisher.setdefault(doc["publisher"], []).append(doc)
    for publisher, docs in by_publisher.items():
        granted = [d for d in docs if d["rights"] == "granted"]
        if granted:
            sources = ", ".join(f"[{d['license_name']}]({d['license_url']})" for d in granted)
            decision = "Granted by license; full copies committed with the license notice"
        else:
            name, url, _ = TERMS[publisher]
            sources, decision = f"[{name}]({url})", "Not granted; linked and reproducible locally"
        lines.append(f"| {publisher} | {sources} | {decision} | {len(docs)} |")
    lines.append("")
    lines += ["## Moonshot AI: why these copies are committed", "",
              "Moonshot AI publishes Kimi K3's technical report in the [Kimi-K3 repository]"
              "(https://github.com/MoonshotAI/Kimi-K3) under the Kimi K3 License. That license defines the "
              "licensed \"Software\" to include \"associated documentation\" and permits anyone to copy, publish, "
              "and distribute it, provided the copyright and permission notice is included. An earlier revision of "
              "this catalog declined to rely on that grant because the license does not name the PDF. On "
              "re-review, the report is documentation published alongside the model in the same repository, so "
              "it falls within that definition. The license's other conditions concern model-as-a-service revenue "
              "and display in large commercial products and do not apply to this repository. The Kimi K2.7 Code "
              "model card is the README of Moonshot AI's Hugging Face repository, released under a Modified MIT "
              "License that likewise covers associated documentation files. Both license texts are committed "
              "beside the copies. Anyone who prefers explicit confirmation can write to `license@moonshot.ai`, "
              "the contact the Kimi K3 License names.", "",
              "## Approval needed for the remaining documents", "",
              "To commit any other PDF or its verbatim extraction, obtain written permission from its publisher "
              "that covers both the unmodified PDF and a complete verbatim Markdown extraction in this public "
              "repository, with attribution. Then:", "",
              "1. Record the grant in `catalog.json`: set `rights` to `granted` and fill in `rights_basis`, "
              "`license_name`, `license_url`, `license_file`, and `license_sha256`.",
              "2. Commit the permission or license text as `license_file` in the model folder.",
              "3. Add `!<slug>/system-card.pdf` and `!<slug>/system-card.md` (or `!<slug>/model-card.md`) negations to `models/.gitignore`.",
              "4. Run `python3 local_cards.py --model <slug>`, then `python3 generate.py --write --check`, and commit.",
              "", "## By document", "",
              "| Document | Publisher | SHA-256 (prefix) | Folders | Decision |", "| --- | --- | --- | --- | --- |"]
    for doc_id, doc in catalog["documents"].items():
        folders = ", ".join(f"[`{m['slug']}`]({m['slug']}/source.md)" for m, _ in users(catalog)[doc_id])
        decision = (f"Granted ({doc['license_name']})" if doc["rights"] == "granted"
                    else "Not granted: needs the publisher's written permission")
        lines.append(f"| [{doc['title']}]({doc['url']}) | {doc['publisher']} | `{doc['sha256'][:12]}` | {folders} | {decision} |")
    lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def render_root(catalog):
    c = counts(catalog)
    return "\n".join([
        "# Model cards for GitHub Copilot models (unofficial)", "", GENERATED, "",
        "> [!IMPORTANT]",
        "> **Not a GitHub product. Not official, endorsed, or supported by GitHub.**",
        ">",
        "> This is an independent reference collection. It is **not** an official GitHub offering, is **not** "
        "supported or maintained by GitHub, and has **not** been reviewed or endorsed by GitHub or by any model "
        "publisher named here. Everything in it is provided **\"as is\", without warranty of any kind**, express "
        "or implied, including any warranty of accuracy, completeness, currency, merchantability, fitness for a "
        "particular purpose, or non-infringement. The author and contributors make **no representations or "
        "warranties** about the content and accept **no liability** for any claim, loss, or damage arising from "
        "its use. **Use it at your own risk.**",
        ">",
        "> Digests, tables, and transcriptions may contain errors or omissions and can fall out of date as models "
        "and documents change. They do not replace the publishers' original documents, and nothing here is legal, "
        "compliance, security, or purchasing advice. Verify anything that matters against the original source "
        "before relying on it.", "",
        "> [!WARNING]",
        "> **Model list disclaimer.** The models listed here do **not** necessarily match the models GitHub "
        "Copilot currently serves, has served, or will serve. Availability, names, release status, and client "
        f"support change frequently, and this catalog reflects GitHub's documentation as checked on "
        f"{catalog['checked_at']}. Always consult GitHub's [supported AI models reference]({SUPPORTED}) for the "
        "authoritative, current list.", "",
        f"A catalog of the models offered in the **GitHub Copilot CLI** and the **GitHub Copilot app**, checked "
        f"{catalog['checked_at']}, with each model's system card or model card from its publisher.", "",
        f"- [**Model catalog and coverage**](models/README.md): {c['models']} folders ({c['current']} current, "
        f"{c['limited']} limited, {c['utility']} utility-only, {c['retired']} retired) and {c['documents']} "
        f"publisher documents ({c['pdf']} PDFs, {c['markdown']} Markdown card).",
        "- Each folder has an original **digest** of capabilities, evaluations, safety findings, limitations, "
        "and practical implications, with page citations, plus **provenance** (owner URL, retrieval date, "
        "size, SHA-256) and **variants**.",
        f"- [**Rights review**](models/RIGHTS.md): {c['granted']} documents are published under a license that "
        f"permits redistribution, stored beside each copy. The other {c['not_granted']} carry no such license and "
        "remain subject to their publishers' terms; a verified local workflow downloads them from the owner URLs "
        "and produces complete page-marked Markdown transcriptions.",
        f"- [**Scope and gaps**](models/README.md#document-scope-and-gaps): {' and '.join(m['name'] for m in catalog['models'] if not m.get('document'))} "
        "have no publisher card; some models are covered by a family or shared card, and each mapping's "
        "evidence is recorded in its `source.md`.", "",
        "Roster evidence comes from GitHub's [supported-models documentation]"
        f"({SUPPORTED}) and the Copilot app's model picker. Documents come only from their publishers: OpenAI, "
        "Anthropic, Google DeepMind, Microsoft, Moonshot AI, and xAI.", "",
        "## Quick start", "", "```sh", "cd models",
        "python3 -m pip install -r requirements-local.txt  # PyMuPDF, used for extraction and checks",
        "python3 local_cards.py --all                      # download, verify, and extract every PDF locally",
        "python3 generate.py --check                       # validate the catalog, digests, and generated files",
        "python3 roster_check.py                           # compare the catalog with GitHub's live tables",
        "```", "",
        "See [models/README.md](models/README.md#maintenance) for maintenance steps.", "",
        "## Ownership, trademarks, and attribution", "",
        "- **Publisher documents belong to their owners.** System cards, model cards, technical reports, and "
        "other publisher documents, including any copy, transcription, or excerpt of them in this repository, "
        "are the property of their respective publishers and copyright holders, who retain all rights. Each "
        "folder's `source.md` names the publisher and links the original.",
        "- **No license is granted to third-party material.** Inclusion here does not license any publisher "
        "document to you. Where a publisher license permits redistribution, that license is stored beside the "
        "copy; otherwise, obtain any permission you need from the rights holder. See [RIGHTS.md](models/RIGHTS.md).",
        "- **Trademarks.** Model, product, and company names (including GitHub, Copilot, OpenAI, GPT, "
        "Anthropic, Claude, Google, Gemini, Microsoft, Moonshot AI, Kimi, xAI, and Grok) are trademarks or "
        "registered trademarks of their respective owners. They are used only to identify the models and "
        "documents and do not imply affiliation, sponsorship, or endorsement.",
        "- **Rights holders.** If you believe material here infringes your rights or should be removed, "
        "[open an issue](https://github.com/IraLeeBell/models/issues) and it will be reviewed and removed or "
        "corrected as appropriate.", "",
        "## License", "",
        "Original material in this repository (digests, generated Markdown, scripts) is under the "
        "[MIT License](LICENSE), which includes its own warranty disclaimer and limitation of liability. The MIT "
        "License does not apply to publisher documents or their transcriptions; those remain under their owners' "
        "terms.", "",
    ])


def outputs(catalog):
    rendered = {ROOT / "README.md": render_index(catalog), ROOT / "RIGHTS.md": render_rights(catalog),
                REPO / "README.md": render_root(catalog)}
    for model in catalog["models"]:
        rendered[ROOT / model["slug"] / "source.md"] = render_source(model, catalog)
        rendered[ROOT / model["slug"] / "variants.md"] = render_variants(model, catalog)
    return rendered


FENCE = re.compile(r"^```.*?^```", re.S | re.M)
CODE_SPAN = re.compile(r"(`+)[^\n]+?\1")
RELATIVE_LINK = re.compile(r"\]\((?![a-z][a-z0-9+.-]*:|#)([^)\s]+)\)")
PATTERN_FILES = {"generate.py", "digest_check.py"}  # define the banned patterns themselves


def sha256(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def tracked_files():
    try:
        result = subprocess.run(["git", "ls-files", "-z", "--cached", "--others", "--exclude-standard"],
                                cwd=REPO, capture_output=True, check=True)
    except (OSError, subprocess.CalledProcessError):
        return None
    return [REPO / name for name in result.stdout.decode().split("\0") if name]


def local_sources(model, catalog, extraction_dir=None):
    """Concatenate whatever full-text sources exist locally for the copy check, or return None."""
    texts = []
    doc_ids = ([model["document"]] if model.get("document") else []) + model.get("supplements", [])
    for doc_id in doc_ids:
        doc = catalog["documents"][doc_id]
        folder = ROOT / model["slug"]
        if doc_id == model.get("document"):
            candidates = [folder / ("system-card.md" if doc["format"] == "pdf" else "model-card.md")]
        else:
            candidates = [folder / "supplements" / f"{doc_id}.md"]
        if extraction_dir:
            candidates.append(Path(extraction_dir) / f"{doc_id}.md")
        found = next((p for p in candidates if p.is_file()), None)
        if found:
            texts.append(found.read_text(encoding="utf-8"))
    return "\n".join(texts) if texts else None


def check(catalog, extraction_dir=None):
    import card_extract  # needs PyMuPDF only for --check; imported lazily so --write stays stdlib-only

    problems, documents = [], catalog["documents"]
    for path, text in outputs(catalog).items():
        if not path.is_file() or path.read_text(encoding="utf-8") != text:
            problems.append(f"{path.relative_to(REPO)} is stale; run generate.py --write")
    slugs = {m["slug"] for m in catalog["models"]}
    folders = {p.name for p in ROOT.iterdir() if p.is_dir() and not p.name.startswith((".", "_"))}
    if folders != slugs:
        problems.append(f"folders differ from catalog: extra {sorted(folders - slugs)}, missing {sorted(slugs - folders)}")
    skipped = []
    for model in catalog["models"]:
        source = local_sources(model, catalog, extraction_dir)
        if source is None and model.get("document"):
            skipped.append(model["slug"])
        problems += digest_check.check(model, documents, ROOT, extraction=source)

    gitignore = (ROOT / ".gitignore").read_text(encoding="utf-8").splitlines()
    for doc_id, doc in documents.items():
        for model, role in users(catalog)[doc_id]:
            if doc["rights"] != "granted" or role != "primary":
                continue
            folder = ROOT / model["slug"]
            license_path = folder / doc["license_file"]
            if not license_path.is_file() or sha256(license_path) != doc["license_sha256"]:
                problems.append(f"{model['slug']}: {doc['license_file']} is missing or differs from the catalog")
            if doc["format"] == "pdf":
                pdf, md = folder / "system-card.pdf", folder / "system-card.md"
                for name in (f"!{model['slug']}/system-card.pdf", f"!{model['slug']}/system-card.md"):
                    if name not in gitignore:
                        problems.append(f".gitignore lacks {name}")
                if not pdf.is_file() or sha256(pdf) != doc["sha256"]:
                    problems.append(f"{model['slug']}: committed PDF is missing or its SHA-256 differs")
                if not md.is_file():
                    problems.append(f"{model['slug']}: committed extraction is missing")
                else:
                    text = md.read_text(encoding="utf-8")
                    if not card_extract.check_markdown(text, doc["pages"]) or doc["sha256"] not in text[:3000]:
                        problems.append(f"{model['slug']}: system-card.md lacks page markers or the PDF's SHA-256")
            else:
                card = folder / "model-card.md"
                if f"!{model['slug']}/model-card.md" not in gitignore:
                    problems.append(f".gitignore lacks !{model['slug']}/model-card.md")
                if not card.is_file() or sha256(card) != doc["sha256"]:
                    problems.append(f"{model['slug']}: model-card.md is missing or differs from the owner file")

    files = tracked_files()
    if files is not None:
        granted = {ROOT / m["slug"] / name for doc_id, doc in documents.items() if doc["rights"] == "granted"
                   for m, role in users(catalog)[doc_id] if role == "primary"
                   for name in ("system-card.pdf", "system-card.md", "model-card.md")}
        committed = set(files)
        committed_dirs = {parent for path in files for parent in path.parents}
        for path in files:
            if path.suffix == ".md" and path.name not in ("system-card.md", "model-card.md") and path.is_file():
                prose = CODE_SPAN.sub("", FENCE.sub("", path.read_text(encoding="utf-8")))
                for target in RELATIVE_LINK.findall(prose):
                    resolved = Path(os.path.normpath(path.parent / target.split("#")[0]))
                    if resolved not in committed and resolved not in committed_dirs:
                        problems.append(f"{path.relative_to(REPO)} links to {target}, which would not be committed")
            if path.suffix.lower() == ".pdf" and path not in granted:
                problems.append(f"{path.relative_to(REPO)} would be committed without a recorded grant")
            if path.name in ("system-card.md", "model-card.md") and path not in granted:
                problems.append(f"{path.relative_to(REPO)} would be committed without a recorded grant")
            verbatim = path.name in ("system-card.md", "model-card.md") or path.name.startswith("LICENSE")
            if path.suffix in (".md", ".json", ".py", ".txt") and not verbatim and path.is_file():
                match = BANNED.search(path.read_text(encoding="utf-8"))
                if match and path.name not in PATTERN_FILES and not path.name.startswith("test_"):
                    problems.append(f"{path.relative_to(REPO)} contains banned text {match.group(0)!r}")
    if skipped:
        print(f"note: copy check skipped for {len(skipped)} digests without a local extraction "
              "(run local_cards.py --all to enable it)")
    return problems


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--write", action="store_true", help="write generated Markdown")
    parser.add_argument("--check", action="store_true", help="verify the repository")
    parser.add_argument("--extraction-dir", type=Path,
                        help="directory of <document-id>.md extractions used for the digest copy check")
    args = parser.parse_args(argv)
    if not (args.write or args.check):
        parser.error("choose --write and/or --check")
    catalog = load_catalog()
    if args.write:
        for path, text in outputs(catalog).items():
            path.parent.mkdir(parents=True, exist_ok=True)
            if not path.is_file() or path.read_text(encoding="utf-8") != text:
                path.write_text(text, encoding="utf-8")
                print(f"wrote {path.relative_to(REPO)}")
    if args.check:
        problems = check(catalog, args.extraction_dir)
        print("\n".join(problems) or f"catalog OK: {len(catalog['models'])} models, {len(catalog['documents'])} documents")
        return 1 if problems else 0
    return 0


if __name__ == "__main__":
    sys.exit(main())
